/**
 * strings.js — 文案字典（移植自 Zepp OS 版 page/i18n/zh-CN.po）
 * 诊断引擎等非组件模块无法使用 $t，统一经 getText(key) 取文案。
 */
const ZH = {
  // --- 通用 UI ---
  ai_pulse: '把脉',
  start_pulse: '开始把脉',
  measuring_pulse: '正在把脉...',
  measurement_complete: '测量完成',
  measurement_failed: '测量失败',
  keep_still: '保持静止...',
  nav_wellness: '养生建议',
  wellness_subtitle: '四时调养',
  pulse_theory: '脉象学原理',
  constitution: '体质',
  six_dimensions: '六维脉象',
  five_organs: '五脏状态',
  view_detail: '详情',
  ai_disclaimer: '本分析仅供参考，不构成医疗诊断',
  no_pulse_data: '暂无脉象数据，请先进行把脉',

  // --- 六维 ---
  dim_rate: '脉数', dim_rhythm: '脉律', dim_strength: '脉势',
  dim_width: '脉形', dim_tension: '紧张度', dim_rsa: '迷走张力',
  dim_desc_rate: '脉率主心跳快慢。当前节律从容，心肺与自主神经调节良好。',
  dim_desc_rhythm: '脉律主心跳匀齐。节律基本规整，偶有微小波动属常态。',
  dim_desc_strength: '脉势主气血盛衰。力度适中，气血运行平稳，无明显偏颇。',
  dim_desc_width: '脉形主血脉通畅。管径适中，血管弹性佳，气血通道畅通。',
  dim_desc_tension: '紧张度主身心张弛。略偏紧张，或与压力疲劳有关，宜放松。',
  dim_desc_rsa: '迷走张力主神经调节。呼吸对心率影响正常，迷走功能良好。',

  // --- 14 脉象 ---
  pulse_name_fu: '浮脉', pulse_desc_fu: '脉位表浅，轻取即得，重按反减。主表证，亦见于虚阳浮越。',
  pulse_name_chen: '沉脉', pulse_desc_chen: '脉位深在，重按始得。主里证，有力里实，无力里虚。',
  pulse_name_chi: '迟脉', pulse_desc_chi: '脉来迟缓，一息不足四至。主寒证，亦见实热内结。',
  pulse_name_shuo: '数脉', pulse_desc_shuo: '脉来急数，一息五至以上。主热证，有力实热，无力虚热。',
  pulse_name_hua: '滑脉', pulse_desc_hua: '往来流利，如珠走盘。主痰饮食滞、实热，亦见健康人。',
  pulse_name_se: '涩脉', pulse_desc_se: '往来艰涩，如轻刀刮竹。主气滞血瘀，精伤血少。',
  pulse_name_xu: '虚脉', pulse_desc_xu: '三部脉举之无力，按之空虚。主虚证，气血阴阳俱不足。',
  pulse_name_shi: '实脉', pulse_desc_shi: '三部脉举按皆有力。主实证，邪气盛而正气不虚。',
  pulse_name_xian: '弦脉', pulse_desc_xian: '脉来绷急，如按琴弦。主肝胆病、痛证，多与压力相关。',
  pulse_name_xi: '细脉', pulse_desc_xi: '脉细如线，应指明显。主气血两虚，湿邪为病。',
  pulse_name_hong: '洪脉', pulse_desc_hong: '脉体宽大有力，来盛去衰。主气分热盛，亦见于夏季常脉。',
  pulse_name_huan: '缓脉', pulse_desc_huan: '脉来和缓，节律均匀。为正常脉象，胃气充足。',
  pulse_name_jie: '结脉', pulse_desc_jie: '脉来缓慢，时有中止，止无定数。主阴盛气结，寒痰血瘀。',
  pulse_name_dai: '代脉', pulse_desc_dai: '脉来中止良久方还，止有定数。主脏气衰微。',

  // --- 9 体质 ---
  const_name_balanced: '平和质', const_desc_balanced: '阴阳调和，气血充盛，体态适中。为最佳体质状态。',
  const_name_qi_def: '气虚质', const_desc_qi_def: '元气不足，疲乏气短，自汗畏风。脏腑功能偏低。',
  const_name_yang_def: '阳虚质', const_desc_yang_def: '阳气不足，畏寒肢冷，精神不振。温煦功能减退。',
  const_name_yin_def: '阴虚质', const_desc_yin_def: '阴液亏少，口燥咽干，手足心热。滋润功能不足。',
  const_name_qi_stag: '气郁质', const_desc_qi_stag: '气机郁滞，神情抑郁，忧虑脆弱。与压力焦虑相关。',
  const_name_blood_stasis: '血瘀质', const_desc_blood_stasis: '血行不畅，肤色晦暗，舌暗瘀斑。微循环功能偏弱。',
  const_name_phlegm_damp: '痰湿质', const_desc_phlegm_damp: '痰湿凝聚，形体肥胖，腹部肥满。代谢运化偏弱。',
  const_name_damp_heat: '湿热质', const_desc_damp_heat: '湿热内蕴，面垢油光，口苦苔黄。代谢炎症倾向。',
  const_name_allergic: '特禀质', const_desc_allergic: '先天失常，过敏体质。对外界刺激反应敏感。',

  // --- 五脏 ---
  organ_name_heart: '心', organ_name_liver: '肝', organ_name_spleen: '脾',
  organ_name_lung: '肺', organ_name_kidney: '肾',
  organ_status_he: '和', organ_status_ping: '平', organ_status_xu: '虚', organ_status_kui: '亏',
  organ_desc_heart_he: '心气充沛，血脉和利，神志清明',
  organ_desc_heart_ping: '心功能正常，注意劳逸结合',
  organ_desc_heart_xu: '心血不足或心气偏虚，易心悸失眠',
  organ_desc_heart_kui: '心阳不振，血行无力，建议调养',
  organ_desc_liver_he: '肝气条达，疏泄正常，情志调畅',
  organ_desc_liver_ping: '肝功能平稳，保持情绪乐观',
  organ_desc_liver_xu: '肝气郁结或肝血不足，易烦躁易怒',
  organ_desc_liver_kui: '肝郁化火或肝阴亏虚，建议疏肝理气',
  organ_desc_spleen_he: '脾气健运，气血生化有源',
  organ_desc_spleen_ping: '脾胃功能正常，饮食有节',
  organ_desc_spleen_xu: '脾气虚弱，运化不足，易疲劳腹胀',
  organ_desc_spleen_kui: '脾阳不足，湿浊内生，建议健脾祛湿',
  organ_desc_lung_he: '肺气宣肃正常，卫外固密',
  organ_desc_lung_ping: '肺功能正常，注意防寒保暖',
  organ_desc_lung_xu: '肺气不足，卫外不固，易感冒气短',
  organ_desc_lung_kui: '肺气虚损，宣降失常，建议补肺益气',
  organ_desc_kidney_he: '肾精充足，元气充沛，骨髓坚固',
  organ_desc_kidney_ping: '肾功能正常，注意勿过劳',
  organ_desc_kidney_xu: '肾气不足或肾阴虚，易腰膝酸软',
  organ_desc_kidney_kui: '肾阳虚衰，精气亏虚，建议温补肾阳',

  // --- 维度等级标签 ---
  dim_label_unknown: '未知', dim_label_ping: '平',
  dim_label_rate_chi: '迟', dim_label_rate_huan: '缓', dim_label_rate_zhong: '中',
  dim_label_rate_pian_shuo: '偏数', dim_label_rate_shuo: '数',
  dim_label_rhythm_jie_dai: '结代', dim_label_rhythm_pian_buqi: '偏不齐',
  dim_label_rhythm_ke: '可', dim_label_rhythm_qi: '齐', dim_label_rhythm_he: '和',
  dim_label_strength_xu: '虚', dim_label_strength_pian_xu: '偏虚',
  dim_label_strength_pian_shi: '偏实', dim_label_strength_shi: '实',
  dim_label_width_xi: '细', dim_label_width_pian_xi: '偏细',
  dim_label_width_pian_hong: '偏洪', dim_label_width_hong: '洪',
  dim_label_tension_ruan: '软', dim_label_tension_ru: '濡',
  dim_label_tension_pian_xian: '偏弦', dim_label_tension_xian: '弦',
  dim_label_rsa_rigid: '迷走迟钝', dim_label_rsa_blunted: '迷走减退',
  dim_label_rsa_normal: '迷走正常', dim_label_rsa_flexible: '迷走灵活',
  dim_label_rsa_highly_flexible: '迷走极佳',

  // --- 养生建议 ---
  rec_cat_diet: '饮食', rec_cat_rest: '作息', rec_cat_exercise: '运动', rec_cat_mind: '情志',
  rec_separator: '；',
  rec_diet_qi_def: '宜食山药、大枣、小米、鸡肉等益气之品',
  rec_diet_yang_def: '宜食羊肉、韭菜、核桃、生姜等温阳之品',
  rec_diet_yin_def: '宜食银耳、百合、枸杞、鸭肉等滋阴之品',
  rec_diet_qi_stag: '宜食玫瑰花茶、柑橘、佛手等理气之品',
  rec_diet_default: '饮食均衡，五谷为养，荤素搭配',
  rec_rest_liver: '建议23:00前入睡，子时养肝血',
  rec_rest_heart: '建议午间小憩15-30分钟，养心安神',
  rec_rest_default: '保持规律作息，保证7-8小时睡眠',
  rec_rest_no_caffeine: '避免熬夜，减少咖啡浓茶摄入',
  rec_exercise_gentle: '宜选择太极、八段锦、散步等柔缓运动，微汗即止',
  rec_exercise_cardio: '宜跑步、游泳、球类等有氧运动，舒展气机',
  rec_exercise_default: '每周3-5次中等强度运动，每次30分钟',
  rec_mind_meditate: '建议练习冥想或正念呼吸，疏解压力',
  rec_mind_social: '多与朋友交流倾诉，培养兴趣爱好转移注意力',
  rec_mind_default: '保持心情愉悦，乐观豁达',
  rec_mind_no_anger: '避免大怒，怒伤肝',
  rec_mind_no_overjoy: '避免过喜，喜伤心',

  // --- 趋势 ---
  trend_insufficient: '数据积累中', trend_stable: '脉象平稳',
  trend_improving: '脉象向好', trend_slightly_improving: '脉象略向好',
  trend_declining: '脉象趋弱', trend_slightly_declining: '脉象略趋弱',

  // --- 脉象学原理 ---
  pulse_theory_subtitle: '源自《黄帝内经》《脉经》《濒湖脉学》',
  pulse_theory_quote: '"脉理精微，其体难辨……在心易了，指下难明。"',
  pulse_theory_quote_author: '——王叔和《脉经·序》',
  pulse_theory_quote_trans: '白话释义：脉象的道理精妙细微，形体难以辨别——心中明白容易，指下描述困难。',
  pulse_theory_origin_title: '渊源',
  pulse_theory_origin_body: '脉诊起源于《黄帝内经·素问》，确立于《难经》，系统整理于西晋王叔和《脉经》三十四卷，至明代李时珍《濒湖脉学》集大成，载二十七脉，流传至今，为中医学最具特色的诊断方法之一。',
  pulse_theory_books_title: '历代脉学要籍',
  pulse_theory_book_neijing: '《黄帝内经》——最早的系统论述',
  pulse_theory_book_nanjing: '《难经》——独取寸口理论',
  pulse_theory_book_maijing: '《脉经》——第一部脉学专著',
  pulse_theory_book_binhu: '《濒湖脉学》——二十七脉定本',
  pulse_theory_cunkou_title: '独取寸口',
  pulse_theory_cunkou_body: '"寸口者，脉之大会，手太阴之动脉也。"五脏六腑之气皆变见于寸口，故独取寸口以决五脏六腑死生吉凶之法。',
  pulse_theory_cunkou_trans: '白话：寸口是脉气汇聚之地，属于手太阴肺经。五脏六腑的变化都会反映在这里，所以通过寸口一处即可诊察全身的健康状况。',
  pulse_theory_guide_title: '脉象与健康',
  pulse_theory_normal_pulse: '平脉：不浮不沉，不大不小，从容和缓，节律均匀。谓之"有胃、有神、有根"，为健康之象。',
  pulse_theory_normal_trans: '白话：不浮不沉、不大不小、从容和缓、节律均匀——这叫"有胃气、有神气、有根气"，是健康的标志。',
  pulse_theory_santi: '有胃、有神、有根',
  pulse_theory_santi_source: '——脉学三要',
  pulse_theory_factors_title: '影响脉象的常见因素',
  pulse_theory_factor_emotion: '紧张焦虑 → 脉多弦',
  pulse_theory_factor_exercise: '活动之后 → 脉偏数',
  pulse_theory_factor_diet: '饱食之后 → 脉偏洪',
  pulse_theory_factor_sleep: '熬夜之后 → 脉细数',
  pulse_theory_reading_tip_title: '阅读提示',
  pulse_theory_reading_tip: '脉象受多种因素影响：情绪波动、运动、饮食、睡眠均可使脉象发生短期变化。单次测量结果仅供日常参考，建议连续多日观察趋势。',
  pulse_theory_disclaimer: '以上内容仅供健康科普参考，不构成医疗诊断。如有身体不适请及时就医。',
};

export function getText(key) {
  return ZH[key] || '';
}
